name: Sky Q Remote Release

on:
  release:
    types: [published]

jobs:
  releasenotes:
    name: Prepare release notes
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      - name: Release Notes
        uses: "rogerselwyn/actions/release-notes@main"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
